import type { Metadata } from "next";
import "./globals.css";
import NavBar from '@/components/layout/Navbar';
import ReactQueryProvider from '@/components/queryClientProvider';
import MSWStart from '@/mocks/MSWstart';
import { AuthProvider } from '@/context/AuthContext';

import Script from "next/script";

const appkey = process.env.NEXT_PUBLIC_KAKAO_APP_KEY; // Kakao API 키를 입력하세요

const src = `https://dapi.kakao.com/v2/maps/sdk.js?appkey=${appkey}&autoload=false`;

export const metadata: Metadata = {
  title: "PhotoMap",
  description: "Generated by PhotoMap",
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <Script 
        src={src} 
        strategy="beforeInteractive"
        type="text/javascript"
      />
      </head>
      <body>
        <MSWStart>
          <ReactQueryProvider>
            <AuthProvider >
              <NavBar />
              {children}
            </AuthProvider>
          </ReactQueryProvider>
        </MSWStart>
      </body>
    </html>
  );
}
