import type { Metadata } from "next";
import "./globals.css";
import NavBar from '@/components/layout/Navbar';
import ReactQueryProvider from '@/components/queryClientProvider';
import MSWStart from '@/mocks/MSWstart';
import { AuthProvider } from '@/context/AuthContext';

export const metadata: Metadata = {
  title: "PhotoMap",
  description: "Generated by PhotoMap",
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MSWStart>
          <ReactQueryProvider>
            <AuthProvider >
              <NavBar />
              {children}
            </AuthProvider>
          </ReactQueryProvider>
        </MSWStart>
      </body>
    </html>
  );
}
